ALTER TABLE "Store" ADD COLUMN "archivedAt" DATETIME;
ALTER TABLE "Product" ADD COLUMN "archivedAt" DATETIME;

ALTER TABLE "Sale" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE "Sale" ADD COLUMN "returnedAt" DATETIME;
ALTER TABLE "Sale" ADD COLUMN "returnedByName" TEXT;
ALTER TABLE "Sale" ADD COLUMN "returnReason" TEXT;
