"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "fr";

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    pos: "Point of Sale",
    sales: "Sales",
    stores: "Stores",
    users: "Users",
    signedInAs: "Signed in as",
    activeStore: "Active store",
    welcomeTo: "Welcome to",
    signOut: "Sign out",
    loadingWorkspace: "Loading workspace…",
    currencyNote: "USD estimates use 600 FCFA = $1 USD",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    markAllRead: "Mark all read",
    clearAll: "Clear all",
    language: "Language",
    english: "English",
    french: "Français",
    addProduct: "Add product",
    editProduct: "Edit product",
    delete: "Delete",
    edit: "Edit",
    search: "Search",
    all: "All",
    loading: "Loading…",
    saveChanges: "Save changes",
    createProduct: "Create product",
    cancel: "Cancel",
    name: "Name",
    category: "Category",
    barcode: "Barcode",
    supplier: "Supplier",
    costFcfa: "Cost (FCFA)",
    sellPriceFcfa: "Sell price (FCFA)",
    quantity: "Quantity",
    lowStockThreshold: "Low stock threshold",
    expiryDate: "Expiry date",
    productImage: "Product image",
    salesHistory: "Sales history",
    completedSalesReturns: "Completed sales and returns for the active store.",
    returns: "Returns",
    payment: "Payment",
    total: "Total",
    status: "Status",
    date: "Date",
    cashier: "Cashier",
    items: "Items",
    completed: "Completed",
    returned: "Returned",
    returnSale: "Return sale",
    addStore: "Add store",
    address: "Address",
    createStore: "Create store",
    addUser: "Add user",
    email: "Email",
    password: "Password",
    role: "Role",
    staff: "Staff",
    admin: "Admin",
    assignedStore: "Assigned store",
    chooseStore: "Choose a store",
    createUser: "Create user",
    inventorySubtitle: "Search, filter, and manage products for the active store.",
    drinks: "Drinks",
    medicine: "Medicine",
    lowStock: "Low stock",
    expired: "Expired",
    searchNameBarcode: "Search name or barcode",
    allSuppliers: "All suppliers",
    price: "Price",
    expiry: "Expiry",
    noProducts: "No products match your filters",
    ok: "OK",
    product: "Product",
    signIn: "Sign in",
    signingIn: "Signing in…",
    loginSubtitle: "Sign in to manage inventory and sales across your stores.",
    posSubtitle: "Scan or search products, build a cart, and complete the sale.",
    searchBarcode: "Search / barcode",
    searchPlaceholder: "Type name or scan barcode, then Enter",
    left: "left",
    cart: "Cart",
    cartEmpty: "Cart is empty",
    item: "Item",
    remove: "Remove",
    paymentMethod: "Payment method",
    cash: "Cash",
    card: "Card",
    subtotal: "Subtotal",
    processing: "Processing…",
    completeSale: "Complete sale",
    productFormSubtitle: "Include barcode, supplier, stock level, and optional image.",
    other: "Other",
    thisStore: "this store",
    required: "required",
    optional: "optional",
    uploading: "Uploading…",
    saving: "Saving…",
    dashboardSubtitle: "Store overview, stock health, and quick actions.",
    newSale: "New sale",
    totalInventory: "Total inventory (SKUs)",
    unitsOnHand: "units on hand",
    inventoryValue: "Inventory value",
    costTimesQuantity: "Cost × quantity",
    lowStockAlerts: "Low stock alerts",
    atBelowThreshold: "At or below threshold",
    expiredMedicine: "Expired medicine",
    nearExpiry: "near expiry",
    recentlyAdded: "Recently added",
    expiryWatch: "Expiry watch",
    noProductsYet: "No products yet",
    noExpiryAlerts: "No expiry alerts",
    allStores: "All stores",
    assignmentSaved: "Store assignment saved",
    enableAlerts: "Enable phone alerts",
    alertsOn: "Phone alerts on",
    disableAlerts: "Turn off phone alerts",
    pushDenied: "Notifications were blocked. Enable them in your browser settings.",
    totalSales: "Total sales",
    totalReturns: "Total returns",
    netSales: "Net sales",
    today: "Today",
    thisWeek: "This week",
    thisMonth: "This month",
    reportRequestSubtitle: "Choose one day or a date range, then generate the report.",
    startDate: "Start date",
    endDate: "End date",
    generateReport: "Generate report",
    generating: "Generating…",
    reportFor: "Report for",
    selectReportDates: "Select a start and end date.",
    invalidDateRange: "The end date must be on or after the start date.",
    reportLoadFailed: "Failed to generate the report.",
    transactions: "transactions",
    salesReport: "Sales report",
    retailValue: "Retail stock value",
    retailValueNote: "Sell price × quantity",
    unitsOnHandLabel: "Units on hand",
    productsCount: "products",
  },
  fr: {
    dashboard: "Tableau de bord",
    inventory: "Inventaire",
    pos: "Point de vente",
    sales: "Ventes",
    stores: "Magasins",
    users: "Utilisateurs",
    signedInAs: "Connecté en tant que",
    activeStore: "Magasin actif",
    welcomeTo: "Bienvenue à",
    signOut: "Se déconnecter",
    loadingWorkspace: "Chargement de l’espace…",
    currencyNote: "Estimation USD : 600 FCFA = 1 $ USD",
    notifications: "Notifications",
    noNotifications: "Aucune notification",
    markAllRead: "Tout marquer comme lu",
    clearAll: "Tout effacer",
    language: "Langue",
    english: "English",
    french: "Français",
    addProduct: "Ajouter un produit",
    editProduct: "Modifier le produit",
    delete: "Supprimer",
    edit: "Modifier",
    search: "Rechercher",
    all: "Tous",
    loading: "Chargement…",
    saveChanges: "Enregistrer",
    createProduct: "Créer le produit",
    cancel: "Annuler",
    name: "Nom",
    category: "Catégorie",
    barcode: "Code-barres",
    supplier: "Fournisseur",
    costFcfa: "Coût (FCFA)",
    sellPriceFcfa: "Prix de vente (FCFA)",
    quantity: "Quantité",
    lowStockThreshold: "Seuil de stock faible",
    expiryDate: "Date d’expiration",
    productImage: "Image du produit",
    salesHistory: "Historique des ventes",
    completedSalesReturns: "Ventes terminées et retours du magasin actif.",
    returns: "Retours",
    payment: "Paiement",
    total: "Total",
    status: "Statut",
    date: "Date",
    cashier: "Caissier",
    items: "Articles",
    completed: "Terminée",
    returned: "Retournée",
    returnSale: "Retourner la vente",
    addStore: "Ajouter un magasin",
    address: "Adresse",
    createStore: "Créer le magasin",
    addUser: "Ajouter un utilisateur",
    email: "E-mail",
    password: "Mot de passe",
    role: "Rôle",
    staff: "Employé",
    admin: "Administrateur",
    assignedStore: "Magasin attribué",
    chooseStore: "Choisir un magasin",
    createUser: "Créer l’utilisateur",
    inventorySubtitle: "Recherchez, filtrez et gérez les produits du magasin actif.",
    drinks: "Boissons",
    medicine: "Médicaments",
    lowStock: "Stock faible",
    expired: "Expiré",
    searchNameBarcode: "Rechercher par nom ou code-barres",
    allSuppliers: "Tous les fournisseurs",
    price: "Prix",
    expiry: "Expiration",
    noProducts: "Aucun produit ne correspond aux filtres",
    ok: "OK",
    product: "Produit",
    signIn: "Se connecter",
    signingIn: "Connexion…",
    loginSubtitle: "Connectez-vous pour gérer l’inventaire et les ventes de vos magasins.",
    posSubtitle: "Scannez ou recherchez des produits, préparez le panier et terminez la vente.",
    searchBarcode: "Recherche / code-barres",
    searchPlaceholder: "Saisissez un nom ou scannez un code-barres, puis Entrée",
    left: "restant",
    cart: "Panier",
    cartEmpty: "Le panier est vide",
    item: "Article",
    remove: "Retirer",
    paymentMethod: "Mode de paiement",
    cash: "Espèces",
    card: "Carte",
    subtotal: "Sous-total",
    processing: "Traitement…",
    completeSale: "Terminer la vente",
    productFormSubtitle: "Ajoutez le code-barres, le fournisseur, le stock et une image facultative.",
    other: "Autre",
    thisStore: "ce magasin",
    required: "obligatoire",
    optional: "facultatif",
    uploading: "Téléversement…",
    saving: "Enregistrement…",
    dashboardSubtitle: "Aperçu du magasin, état des stocks et actions rapides.",
    newSale: "Nouvelle vente",
    totalInventory: "Inventaire total (UGS)",
    unitsOnHand: "unités en stock",
    inventoryValue: "Valeur de l’inventaire",
    costTimesQuantity: "Coût × quantité",
    lowStockAlerts: "Alertes de stock faible",
    atBelowThreshold: "Au seuil ou en dessous",
    expiredMedicine: "Médicaments expirés",
    nearExpiry: "bientôt expirés",
    recentlyAdded: "Ajouts récents",
    expiryWatch: "Suivi des expirations",
    noProductsYet: "Aucun produit",
    noExpiryAlerts: "Aucune alerte d’expiration",
    allStores: "Tous les magasins",
    assignmentSaved: "Attribution du magasin enregistrée",
    enableAlerts: "Activer les alertes téléphone",
    alertsOn: "Alertes téléphone activées",
    disableAlerts: "Désactiver les alertes téléphone",
    pushDenied: "Les notifications sont bloquées. Activez-les dans les réglages du navigateur.",
    totalSales: "Ventes totales",
    totalReturns: "Retours totaux",
    netSales: "Ventes nettes",
    today: "Aujourd’hui",
    thisWeek: "Cette semaine",
    thisMonth: "Ce mois",
    reportRequestSubtitle: "Choisissez un jour ou une plage de dates, puis générez le rapport.",
    startDate: "Date de début",
    endDate: "Date de fin",
    generateReport: "Générer le rapport",
    generating: "Génération…",
    reportFor: "Rapport du",
    selectReportDates: "Sélectionnez une date de début et de fin.",
    invalidDateRange: "La date de fin doit être égale ou postérieure à la date de début.",
    reportLoadFailed: "Impossible de générer le rapport.",
    transactions: "transactions",
    salesReport: "Rapport des ventes",
    retailValue: "Valeur de vente du stock",
    retailValueNote: "Prix de vente × quantité",
    unitsOnHandLabel: "Unités en stock",
    productsCount: "produits",
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("kasuwa-language");
    if (saved === "en" || saved === "fr") {
      setLanguageState(saved);
      document.documentElement.lang = saved;
    }
  }, []);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage(next) {
        setLanguageState(next);
        localStorage.setItem("kasuwa-language", next);
        document.documentElement.lang = next;
      },
      t(key) {
        return translations[language][key] || translations.en[key] || key;
      },
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
