"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "fr";

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    pos: "Point of Sale",
    sales: "Sales",
    stores: "Stores",
    users: "Users",
    signedInAs: "Signed in as",
    activeStore: "Active store",
    welcomeTo: "Welcome to",
    saleDate: "Sale date",
    lateSaleHint: "Choose today for a normal sale, or an earlier date for a late sale.",
    topSellingProducts: "Top 5 selling products",
    noSalesYet: "No sales recorded yet",
    noSalesInRange: "No sales in this date range",
    salesByCategory: "Sales by category",
    categories: "Categories",
    categoriesSubtitle: "Create and manage product categories used across inventory.",
    addCategory: "Add category",
    createCategory: "Create category",
    categoryNamePlaceholder: "e.g. Plastic bags, AC parts, Taxes",
    requiresExpiry: "Requires expiry date",
    noCategories: "No categories yet",
    categorySaved: "Category saved",
    categoryUpdated: "Category updated",
    categoryDeleted: "Category deleted",
    categoryLoadFailed: "Failed to load categories",
    categorySaveFailed: "Failed to save category",
    categoryDeleteFailed: "Failed to delete category",
    yes: "Yes",
    no: "No",
    signOut: "Sign out",
    loadingWorkspace: "Loading workspace…",
    currencyNote: "USD estimates use 600 FCFA = $1 USD",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    markAllRead: "Mark all read",
    clearAll: "Clear all",
    language: "Language",
    english: "English",
    french: "Français",
    addProduct: "Add product",
    editProduct: "Edit product",
    delete: "Delete",
    edit: "Edit",
    search: "Search",
    all: "All",
    loading: "Loading…",
    saveChanges: "Save changes",
    createProduct: "Create product",
    cancel: "Cancel",
    name: "Name",
    category: "Category",
    barcode: "Barcode",
    supplier: "Supplier",
    costFcfa: "Cost (FCFA)",
    sellPriceFcfa: "Sell price (FCFA)",
    quantity: "Quantity",
    lowStockThreshold: "Low stock threshold",
    expiryDate: "Expiry date",
    productImage: "Product image",
    salesHistory: "Sales history",
    salesPageSubtitle: "View sales totals by date range, or open Sales history for individual transactions.",
    reportTimelineSubtitle: "Totals update automatically for the selected date range.",
    completedSalesReturns: "Completed sales and returns for the active store.",
    returns: "Returns",
    payment: "Payment",
    total: "Total",
    status: "Status",
    date: "Date",
    cashier: "Cashier",
    items: "Items",
    completed: "Completed",
    returned: "Returned",
    returnSale: "Return sale",
    editSale: "Edit sale",
    deleteSale: "Delete sale",
    confirmDeleteSale:
      "Permanently delete this sale? For completed sales, items will be added back to inventory.",
    confirmDeleteReturnedSale:
      "Permanently delete this returned sale? Inventory will not change (already restored on return).",
    saleUpdated: "Sale updated",
    saleDeleted: "Sale deleted",
    saleUpdateFailed: "Failed to update sale",
    saleDeleteFailed: "Failed to delete sale",
    editingSale: "Edit sale",
    saveSale: "Save sale",
    lineQuantities: "Line quantities",
    addStore: "Add store",
    address: "Address",
    createStore: "Create store",
    addUser: "Add user",
    email: "Email",
    password: "Password",
    role: "Role",
    staff: "Staff",
    admin: "Admin",
    assignedStore: "Assigned store",
    chooseStore: "Choose a store",
    createUser: "Create user",
    inventorySubtitle: "Search, filter, and manage products for the active store.",
    drinks: "Drinks",
    medicine: "Medicine",
    lowStock: "Low stock",
    expired: "Expired",
    searchNameBarcode: "Search name or barcode",
    allSuppliers: "All suppliers",
    price: "Price",
    expiry: "Expiry",
    noProducts: "No products match your filters",
    ok: "OK",
    product: "Product",
    signIn: "Sign in",
    signingIn: "Signing in…",
    loginSubtitle: "Sign in to manage inventory and sales across your stores.",
    concurrentLoginHint: "Admin and staff can stay signed in at the same time on different phones or browsers. On the same browser, only one account can be signed in.",
    noStoreAssigned: "No store is assigned to this account. Ask an admin to assign a store under Users.",
    posSubtitle: "Scan or search products, build a cart, and complete the sale.",
    searchBarcode: "Search / barcode",
    searchPlaceholder: "Type name or scan barcode, then Enter",
    left: "left",
    cart: "Cart",
    cartEmpty: "Cart is empty",
    item: "Item",
    remove: "Remove",
    paymentMethod: "Payment method",
    cash: "Cash",
    card: "Card",
    subtotal: "Subtotal",
    processing: "Processing…",
    completeSale: "Complete sale",
    productFormSubtitle: "Include barcode, supplier, stock level, and optional image.",
    other: "Other",
    thisStore: "this store",
    required: "required",
    optional: "optional",
    uploading: "Uploading…",
    saving: "Saving…",
    dashboardSubtitle: "Store overview, stock health, and quick actions.",
    newSale: "New sale",
    totalInventory: "Total inventory (SKUs)",
    unitsOnHand: "units on hand",
    inventoryValue: "Inventory value",
    costTimesQuantity: "Cost × quantity",
    lowStockAlerts: "Low stock alerts",
    atBelowThreshold: "At or below threshold",
    expiredMedicine: "Expired medicine",
    nearExpiry: "near expiry",
    recentlyAdded: "Recently added",
    showTopSelling: "Show top selling products",
    hideTopSelling: "Hide top selling products",
    switchToStaffView: "Switch to staff view",
    switchToAdminView: "Switch to admin view",
    editUser: "Edit user",
    username: "Username",
    usernameOptionalHint: "Optional — defaults from email",
    emailOrUsername: "Email or username",
    emailOrUsernamePlaceholder: "email@store.com or username",
    newPassword: "New password",
    newPasswordHint: "Leave blank to keep the current password",
    userUpdated: "User updated",
    usersSubtitle: "Create admin and staff accounts, edit names, usernames, emails and passwords, and assign store access.",
    customers: "Customers",
    customersSubtitle: "Customers who have placed sales with contact details.",
    saleComplete: "Sale complete",
    customer: "Customer",
    customerDetails: "Customer details",
    customerName: "Customer name",
    customerPhone: "Phone",
    customerEmail: "Email",
    emailReceipt: "Email receipt",
    smsReceipt: "SMS receipt",
    printReceipt: "Print receipt",
    sendReceipt: "Send receipt",
    receiptEmailed: "Receipt emailed",
    receiptSmsSent: "Receipt sent by SMS",
    receiptSendFailed: "Failed to send receipt",
    receiptEmailFailed: "Failed to email receipt",
    receiptSmsFailed: "Failed to send SMS receipt",
    noCustomerContact: "Add a phone or email to send a receipt",
    addedBy: "Added by",
    dateAdded: "Date added",
    dateAddedHint: "When this product was added to inventory. Defaults to today.",
    expiryWatch: "Expiry watch",
    noProductsYet: "No products yet",
    noExpiryAlerts: "No expiry alerts",
    allStores: "All stores",
    assignmentSaved: "Store assignment saved",
    enableAlerts: "Enable phone alerts",
    alertsOn: "Phone alerts on",
    disableAlerts: "Turn off phone alerts",
    pushDenied: "Notifications were blocked. Enable them in your browser settings.",
    totalSales: "Total sales",
    totalReturns: "Total returns",
    netSales: "Net sales",
    today: "Today",
    thisWeek: "This week",
    thisMonth: "This month",
    reportRequestSubtitle: "Choose one day or a date range, then generate the report.",
    startDate: "Start date",
    endDate: "End date",
    generateReport: "Generate report",
    generating: "Generating…",
    reportFor: "Report for",
    selectReportDates: "Select a start and end date.",
    invalidDateRange: "The end date must be on or after the start date.",
    reportLoadFailed: "Failed to generate the report.",
    transactions: "transactions",
    salesReport: "Sales report",
    expenses: "Expenses",
    expensesSubtitle: "Track shop bills, salaries, repairs, and other costs for the active store.",
    addExpense: "Add expense",
    expenseDescription: "Description",
    expenseDescriptionPlaceholder: "e.g. Electricity, salaries, plastic bags, AC repair",
    amountFcfa: "Amount (FCFA)",
    amount: "Amount",
    saveExpense: "Save expense",
    totalExpenses: "Total expenses",
    noExpenses: "No expenses recorded yet",
    recordedBy: "Recorded by",
    expenseSaved: "Expense saved",
    expenseUpdated: "Expense updated",
    expenseDeleted: "Expense deleted",
    invalidExpense: "Enter a valid date, description, and amount.",
    expenseLoadFailed: "Failed to load expenses",
    expenseSaveFailed: "Failed to save expense",
    expenseDeleteFailed: "Failed to delete expense",
    searchExpenses: "Search expenses",
    searchExpensesPlaceholder: "Search by description, amount, date, or person",
    clearSearch: "Clear",
    noExpensesMatch: "No expenses match your search",
    retailValue: "Retail stock value",
    retailValueNote: "Sell price × quantity",
    unitsOnHandLabel: "Units on hand",
    productsCount: "products",
  },
  fr: {
    dashboard: "Tableau de bord",
    inventory: "Inventaire",
    pos: "Point de vente",
    sales: "Ventes",
    stores: "Magasins",
    users: "Utilisateurs",
    signedInAs: "Connecté en tant que",
    activeStore: "Magasin actif",
    welcomeTo: "Bienvenue à",
    saleDate: "Date de vente",
    lateSaleHint: "Choisissez aujourd’hui pour une vente normale, ou une date antérieure pour une vente en retard.",
    topSellingProducts: "Top 5 des produits vendus",
    noSalesYet: "Aucune vente enregistrée",
    noSalesInRange: "Aucune vente sur cette période",
    salesByCategory: "Ventes par catégorie",
    categories: "Catégories",
    categoriesSubtitle: "Créez et gérez les catégories de produits de l’inventaire.",
    addCategory: "Ajouter une catégorie",
    createCategory: "Créer la catégorie",
    categoryNamePlaceholder: "ex. Sacs plastiques, pièces clim, Taxes",
    requiresExpiry: "Nécessite une date d’expiration",
    noCategories: "Aucune catégorie",
    categorySaved: "Catégorie enregistrée",
    categoryUpdated: "Catégorie mise à jour",
    categoryDeleted: "Catégorie supprimée",
    categoryLoadFailed: "Impossible de charger les catégories",
    categorySaveFailed: "Impossible d’enregistrer la catégorie",
    categoryDeleteFailed: "Impossible de supprimer la catégorie",
    yes: "Oui",
    no: "Non",
    signOut: "Se déconnecter",
    loadingWorkspace: "Chargement de l’espace…",
    currencyNote: "Estimation USD : 600 FCFA = 1 $ USD",
    notifications: "Notifications",
    noNotifications: "Aucune notification",
    markAllRead: "Tout marquer comme lu",
    clearAll: "Tout effacer",
    language: "Langue",
    english: "English",
    french: "Français",
    addProduct: "Ajouter un produit",
    editProduct: "Modifier le produit",
    delete: "Supprimer",
    edit: "Modifier",
    search: "Rechercher",
    all: "Tous",
    loading: "Chargement…",
    saveChanges: "Enregistrer",
    createProduct: "Créer le produit",
    cancel: "Annuler",
    name: "Nom",
    category: "Catégorie",
    barcode: "Code-barres",
    supplier: "Fournisseur",
    costFcfa: "Coût (FCFA)",
    sellPriceFcfa: "Prix de vente (FCFA)",
    quantity: "Quantité",
    lowStockThreshold: "Seuil de stock faible",
    expiryDate: "Date d’expiration",
    productImage: "Image du produit",
    salesHistory: "Historique des ventes",
    salesPageSubtitle: "Consultez les totaux par période, ou ouvrez l’historique des ventes pour chaque transaction.",
    reportTimelineSubtitle: "Les totaux se mettent à jour automatiquement pour la période sélectionnée.",
    completedSalesReturns: "Ventes terminées et retours du magasin actif.",
    returns: "Retours",
    payment: "Paiement",
    total: "Total",
    status: "Statut",
    date: "Date",
    cashier: "Caissier",
    items: "Articles",
    completed: "Terminée",
    returned: "Retournée",
    returnSale: "Retourner la vente",
    editSale: "Modifier la vente",
    deleteSale: "Supprimer la vente",
    confirmDeleteSale:
      "Supprimer définitivement cette vente ? Pour une vente terminée, les articles seront remis en stock.",
    confirmDeleteReturnedSale:
      "Supprimer définitivement cette vente retournée ? Le stock ne changera pas (déjà restauré au retour).",
    saleUpdated: "Vente mise à jour",
    saleDeleted: "Vente supprimée",
    saleUpdateFailed: "Impossible de mettre à jour la vente",
    saleDeleteFailed: "Impossible de supprimer la vente",
    editingSale: "Modifier la vente",
    saveSale: "Enregistrer la vente",
    lineQuantities: "Quantités des lignes",
    addStore: "Ajouter un magasin",
    address: "Adresse",
    createStore: "Créer le magasin",
    addUser: "Ajouter un utilisateur",
    email: "E-mail",
    password: "Mot de passe",
    role: "Rôle",
    staff: "Employé",
    admin: "Administrateur",
    assignedStore: "Magasin attribué",
    chooseStore: "Choisir un magasin",
    createUser: "Créer l’utilisateur",
    inventorySubtitle: "Recherchez, filtrez et gérez les produits du magasin actif.",
    drinks: "Boissons",
    medicine: "Médicaments",
    lowStock: "Stock faible",
    expired: "Expiré",
    searchNameBarcode: "Rechercher par nom ou code-barres",
    allSuppliers: "Tous les fournisseurs",
    price: "Prix",
    expiry: "Expiration",
    noProducts: "Aucun produit ne correspond aux filtres",
    ok: "OK",
    product: "Produit",
    signIn: "Se connecter",
    signingIn: "Connexion…",
    loginSubtitle: "Connectez-vous pour gérer l’inventaire et les ventes de vos magasins.",
    concurrentLoginHint: "L’admin et le personnel peuvent rester connectés en même temps sur des téléphones ou navigateurs différents. Sur le même navigateur, un seul compte peut être connecté.",
    noStoreAssigned: "Aucun magasin n’est attribué à ce compte. Demandez à un administrateur de l’attribuer dans Utilisateurs.",
    posSubtitle: "Scannez ou recherchez des produits, préparez le panier et terminez la vente.",
    searchBarcode: "Recherche / code-barres",
    searchPlaceholder: "Saisissez un nom ou scannez un code-barres, puis Entrée",
    left: "restant",
    cart: "Panier",
    cartEmpty: "Le panier est vide",
    item: "Article",
    remove: "Retirer",
    paymentMethod: "Mode de paiement",
    cash: "Espèces",
    card: "Carte",
    subtotal: "Sous-total",
    processing: "Traitement…",
    completeSale: "Terminer la vente",
    productFormSubtitle: "Ajoutez le code-barres, le fournisseur, le stock et une image facultative.",
    other: "Autre",
    thisStore: "ce magasin",
    required: "obligatoire",
    optional: "facultatif",
    uploading: "Téléversement…",
    saving: "Enregistrement…",
    dashboardSubtitle: "Aperçu du magasin, état des stocks et actions rapides.",
    newSale: "Nouvelle vente",
    totalInventory: "Inventaire total (UGS)",
    unitsOnHand: "unités en stock",
    inventoryValue: "Valeur de l’inventaire",
    costTimesQuantity: "Coût × quantité",
    lowStockAlerts: "Alertes de stock faible",
    atBelowThreshold: "Au seuil ou en dessous",
    expiredMedicine: "Médicaments expirés",
    nearExpiry: "bientôt expirés",
    recentlyAdded: "Ajouts récents",
    showTopSelling: "Afficher les produits les plus vendus",
    hideTopSelling: "Masquer les produits les plus vendus",
    switchToStaffView: "Passer en vue personnel",
    switchToAdminView: "Passer en vue admin",
    editUser: "Modifier l’utilisateur",
    username: "Nom d’utilisateur",
    usernameOptionalHint: "Facultatif — généré depuis l’e-mail",
    emailOrUsername: "E-mail ou nom d’utilisateur",
    emailOrUsernamePlaceholder: "email@magasin.com ou nom d’utilisateur",
    newPassword: "Nouveau mot de passe",
    newPasswordHint: "Laissez vide pour conserver le mot de passe actuel",
    userUpdated: "Utilisateur mis à jour",
    usersSubtitle: "Créez des comptes admin et personnel, modifiez noms, identifiants, e-mails et mots de passe, et attribuez l’accès au magasin.",
    customers: "Clients",
    customersSubtitle: "Clients ayant des ventes avec des coordonnées.",
    saleComplete: "Vente terminée",
    customer: "Client",
    customerDetails: "Informations client",
    customerName: "Nom du client",
    customerPhone: "Téléphone",
    customerEmail: "E-mail",
    emailReceipt: "Envoyer le reçu par e-mail",
    smsReceipt: "Envoyer le reçu par SMS",
    printReceipt: "Imprimer le reçu",
    sendReceipt: "Envoyer le reçu",
    receiptEmailed: "Reçu envoyé par e-mail",
    receiptSmsSent: "Reçu envoyé par SMS",
    receiptSendFailed: "Échec de l’envoi du reçu",
    receiptEmailFailed: "Échec de l’envoi du reçu par e-mail",
    receiptSmsFailed: "Échec de l’envoi du reçu par SMS",
    noCustomerContact: "Ajoutez un téléphone ou un e-mail pour envoyer un reçu",
    addedBy: "Ajouté par",
    dateAdded: "Date d’ajout",
    dateAddedHint: "Date d’ajout du produit à l’inventaire. Aujourd’hui par défaut.",
    expiryWatch: "Suivi des expirations",
    noProductsYet: "Aucun produit",
    noExpiryAlerts: "Aucune alerte d’expiration",
    allStores: "Tous les magasins",
    assignmentSaved: "Attribution du magasin enregistrée",
    enableAlerts: "Activer les alertes téléphone",
    alertsOn: "Alertes téléphone activées",
    disableAlerts: "Désactiver les alertes téléphone",
    pushDenied: "Les notifications sont bloquées. Activez-les dans les réglages du navigateur.",
    totalSales: "Ventes totales",
    totalReturns: "Retours totaux",
    netSales: "Ventes nettes",
    today: "Aujourd’hui",
    thisWeek: "Cette semaine",
    thisMonth: "Ce mois",
    reportRequestSubtitle: "Choisissez un jour ou une plage de dates, puis générez le rapport.",
    startDate: "Date de début",
    endDate: "Date de fin",
    generateReport: "Générer le rapport",
    generating: "Génération…",
    reportFor: "Rapport du",
    selectReportDates: "Sélectionnez une date de début et de fin.",
    invalidDateRange: "La date de fin doit être égale ou postérieure à la date de début.",
    reportLoadFailed: "Impossible de générer le rapport.",
    transactions: "transactions",
    salesReport: "Rapport des ventes",
    expenses: "Dépenses",
    expensesSubtitle: "Suivez les factures, salaires, réparations et autres coûts du magasin actif.",
    addExpense: "Ajouter une dépense",
    expenseDescription: "Description",
    expenseDescriptionPlaceholder: "ex. Électricité, salaires, sacs plastiques, réparation clim",
    amountFcfa: "Montant (FCFA)",
    amount: "Montant",
    saveExpense: "Enregistrer la dépense",
    totalExpenses: "Total des dépenses",
    noExpenses: "Aucune dépense enregistrée",
    recordedBy: "Enregistré par",
    expenseSaved: "Dépense enregistrée",
    expenseUpdated: "Dépense mise à jour",
    expenseDeleted: "Dépense supprimée",
    invalidExpense: "Saisissez une date, une description et un montant valides.",
    expenseLoadFailed: "Impossible de charger les dépenses",
    expenseSaveFailed: "Impossible d’enregistrer la dépense",
    expenseDeleteFailed: "Impossible de supprimer la dépense",
    searchExpenses: "Rechercher des dépenses",
    searchExpensesPlaceholder: "Rechercher par description, montant, date ou personne",
    clearSearch: "Effacer",
    noExpensesMatch: "Aucune dépense ne correspond à votre recherche",
    retailValue: "Valeur de vente du stock",
    retailValueNote: "Prix de vente × quantité",
    unitsOnHandLabel: "Unités en stock",
    productsCount: "produits",
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("kasuwa-language");
    if (saved === "en" || saved === "fr") {
      setLanguageState(saved);
      document.documentElement.lang = saved;
    }
  }, []);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage(next) {
        setLanguageState(next);
        localStorage.setItem("kasuwa-language", next);
        document.documentElement.lang = next;
      },
      t(key) {
        return translations[language][key] || translations.en[key] || key;
      },
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
